- name: Run show run on Cisco devices
  hosts: CNBJSoCFW0
  gather_facts: no
  vars:
    ansible_network_os: cisco.asa.asa
    ansible_connection: ansible.netcommon.network_cli
    ansible_ssh_args: "-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss -o Ciphers=+3des-cbc"
  tasks:
    - name: Show running configuration
      ansible.netcommon.asa_command:
        command: show running-config
      register: output

    - name: Display the running configuration
      debug:
        var: output.stdout_lines
