- name: Run show run on Cisco devices
  hosts: CNBJS-LSR0
  gather_facts: no
  vars:
    ansible_network_os: cisco.ios.ios
    ansible_connection: ansible.netcommon.network_cli
  tasks:
    - name: Show running configuration
      ansible.netcommon.cli_command:
        command: show running-config
      register: output

    - name: Display the running configuration
      debug:
        var: output.stdout_lines
