---
- name: Run show run on Cisco devices
  hosts: CNBJSoCFW0
  gather_facts: false
  connection: network_cli

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.asa.asa
    ansible_network_cli_ssh_type: paramiko
    ansible_python_interpreter: python

  collections:
    - cisco.asa

  tasks:
    - name: Show running configuration
      cisco.asa.asa_command:
        commands:
        - show version

      register: output

    - name: Display the running configuration
      debug:
        var: output.stdout_lines
