- name: save result to a file
  hosts: CNBJSoCFW0
  gather_facts: false
  vars:
    ansible_ssh_args: "-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss -o Ciphers=+3des-cbc"

  tasks:
   - name: show cur config
     raw: "show running-config"

     register: print_output

   - debug: var=print_output.stdout_lines