- name: Run show run on Cisco devices
  hosts: all
  gather_facts: no
  vars:
    ansible_network_os: cisco.ios
  tasks:
    - name: Show running configuration
      ansible.netcommon.cli_command:
        command: show running-config
      register: output

    - name: Display the running configuration
      debug:
        var: output.stdout_lines
