---
- name: Show version for the ASA
  gather_facts: false
  hosts: CNBJSoCFW0
  vars:
    ansible_connection: paramiko
    ansible_network_os: cisco.asa.asa
    ansible_ssh_args: "-o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-dss -o Ciphers=+3des-cbc"

  collections:
    - cisco.asa

  tasks:
    - name: Show the ASA version
      cisco.asa.asa_command:
        commands:
        - show version
        - show memory

      register: output

    - name: Display the running configuration
      debug:
        var: output.stdout_lines